"""ep-parity init: Interactive setup wizard for first-time configuration."""

import os
from pathlib import Path
from urllib.parse import quote_plus

import click

from ep_parity.utils.logging import get_logger

logger = get_logger("cli.init")

# All 5 database targets with their connection details
DB_TARGETS: list[dict[str, str]] = [
    {
        "code": "ep15-dev",
        "label": "EP 1.5 Dev",
        "env": "dev",
        "host": "primary-portal-db.dev.internal.marathon-health.com",
        "dbname": "portal_dev",
        "env_var": "DB_EP15_DEV_URI",
    },
    {
        "code": "ep15-qa",
        "label": "EP 1.5 QA",
        "env": "qa",
        "host": "primary-portal-db.qa.internal.marathon-health.com",
        "dbname": "portal_qa",
        "env_var": "DB_EP15_QA_URI",
    },
    {
        "code": "ep20-dev",
        "label": "EP 2.0 Dev",
        "env": "dev",
        "host": "primary-pariveda-db.dev.internal.marathon-health.com",
        "dbname": "pariveda_dev",
        "env_var": "DB_EP20_DEV_URI",
    },
    {
        "code": "ep20-qa",
        "label": "EP 2.0 QA",
        "env": "qa",
        # Hostname misspelling is intentional — this is the real hostname
        "host": "primary-parevida-db.qa.internal.marathon-health.com",
        "dbname": "portal_qa",
        "env_var": "DB_EP20_QA_URI",
    },
    {
        "code": "prod",
        "label": "Production",
        "env": "prod",
        "host": "primary-portal-db.prod.internal.marathon-health.com",
        "dbname": "portal_production",
        "env_var": "DB_PRODUCTION_URI",
    },
]

# Group targets by environment for credential prompting
ENV_GROUPS = [
    ("dev", "Dev", "EP 1.5 Dev + EP 2.0 Dev databases"),
    ("qa", "QA", "EP 1.5 QA + EP 2.0 QA databases (most common for parity testing)"),
    ("prod", "Production", "Production database (read-only, both processors share this DB)"),
]


def _build_uri(username: str, password: str, host: str, dbname: str) -> str:
    """Build a PostgreSQL URI with properly escaped credentials."""
    safe_user = quote_plus(username)
    safe_pass = quote_plus(password)
    return f"postgresql://{safe_user}:{safe_pass}@{host}:5432/{dbname}"


def _mask_password(uri: str) -> str:
    """Show URI with password masked for confirmation display."""
    import re
    return re.sub(r"://([^:]+):([^@]+)@", r"://\1:****@", uri)


def _write_env_file(
    output_path: Path,
    env_credentials: dict[str, tuple[str, str]],
) -> None:
    """Write .env file with database URIs for all configured environments.

    Args:
        output_path: Path to write the .env file.
        env_credentials: Dict of {env_name: (username, password)} for configured
            environments. Environments not in this dict are commented out.
    """
    lines = [
        "# EP Parity Database Credentials",
        "# Generated by 'ep-parity init'",
        "# NEVER commit this file to version control.",
        "# To edit credentials later, modify this file directly or re-run 'ep-parity init'.",
        "",
    ]

    for target in DB_TARGETS:
        env_name = target["env"]
        if env_name in env_credentials:
            username, password = env_credentials[env_name]
            uri = _build_uri(username, password, target["host"], target["dbname"])
            lines.append(f"# {target['label']}")
            lines.append(f"{target['env_var']}={uri}")
        else:
            lines.append(f"# {target['label']} (not configured — re-run 'ep-parity init' or edit manually)")
            lines.append(f"# {target['env_var']}=")
        lines.append("")

    output_path.write_text("\n".join(lines))


def _write_paths_config(
    output_path: Path, base_path: str, sql_directory: str, db_target: str
) -> None:
    """Write paths_config.ini file."""
    lines = [
        "[paths]",
        f"base_path = {base_path}",
        f"sql_directory = {sql_directory}",
        "",
        "[output]",
        "directory_format = {emp_id} {date} {time}",
        "date_format = %%m-%%d-%%y %%H%%M",
        "",
        "[defaults]",
        f"db_target = {db_target}",
        "",
    ]
    output_path.write_text("\n".join(lines))


@click.command()
@click.option(
    "--non-interactive",
    is_flag=True,
    help="Read from environment variables instead of prompting (for CI/automation).",
)
@click.pass_context
def init(ctx: click.Context, non_interactive: bool) -> None:
    """Interactive setup wizard for first-time configuration.

    Creates .env and paths_config.ini with your database credentials
    and directory paths. Handles password escaping automatically.

    Credentials are collected per environment (Dev, QA, Prod) since
    passwords may differ. Environments can be skipped if you don't
    have access.

    Examples:

        ep-parity init

        EP_INIT_QA_USER=jane EP_INIT_QA_PASS=secret \\
            ep-parity init --non-interactive
    """
    config_dir = Path(ctx.obj.get("config_dir") or ".")
    env_path = config_dir / ".env"
    paths_path = config_dir / "paths_config.ini"

    click.echo("")
    click.echo("EP Parity -- First-Time Setup")
    click.echo("=" * 40)
    click.echo("")
    click.echo("This will create .env and paths_config.ini")
    click.echo(f"in: {config_dir.resolve()}")
    click.echo("")

    # Check for existing files
    for path, name in [(env_path, ".env"), (paths_path, "paths_config.ini")]:
        if path.exists():
            if non_interactive:
                click.echo(f"  Overwriting existing {name}")
            elif not click.confirm(f"  {name} already exists. Overwrite?", default=False):
                click.echo(f"  Keeping existing {name}")
                if name == ".env":
                    env_path = None
                else:
                    paths_path = None

    if env_path is None and paths_path is None:
        click.echo("\nNothing to do. Both files kept as-is.")
        return

    # --- Collect credentials per environment ---
    env_credentials: dict[str, tuple[str, str]] = {}

    if env_path is not None:
        click.echo("\nDatabase Credentials:")
        click.echo("  Credentials are collected per environment (passwords may differ).")
        click.echo("  Skip any environment you don't have access to.")
        click.echo("")

        if non_interactive:
            for env_name, env_label, _ in ENV_GROUPS:
                user_var = f"EP_INIT_{env_name.upper()}_USER"
                pass_var = f"EP_INIT_{env_name.upper()}_PASS"
                username = os.environ.get(user_var, "")
                password = os.environ.get(pass_var, "")
                if username and password:
                    env_credentials[env_name] = (username, password)
                    click.echo(f"  {env_label}: configured from {user_var}/{pass_var}")

            if not env_credentials:
                click.echo("  [FAIL] At least one environment must be configured.")
                click.echo("  Set EP_INIT_QA_USER and EP_INIT_QA_PASS (or DEV or PROD).")
                raise SystemExit(1)
        else:
            for env_name, env_label, env_desc in ENV_GROUPS:
                click.echo(f"  {env_label} — {env_desc}")
                if click.confirm(f"    Configure {env_label}?", default=(env_name == "qa")):
                    username = click.prompt(f"    Username for {env_label}")
                    password = click.prompt(f"    Password for {env_label}", hide_input=True)
                    env_credentials[env_name] = (username, password)
                else:
                    click.echo(f"    Skipping {env_label}")
                click.echo("")

            if not env_credentials:
                click.echo("  [FAIL] At least one environment must be configured.")
                raise SystemExit(1)

        # Show configured URIs
        click.echo("  Configured database URIs:")
        for target in DB_TARGETS:
            if target["env"] in env_credentials:
                username, password = env_credentials[target["env"]]
                uri = _build_uri(username, password, target["host"], target["dbname"])
                click.echo(f"    {target['label']:16s} {_mask_password(uri)}")
            else:
                click.echo(f"    {target['label']:16s} (skipped)")

    # --- Collect paths ---
    if paths_path is not None:
        click.echo("\nPaths:")
        default_user = os.getenv("USER", "user")
        default_base = f"/Users/{default_user}/Documents/Parity Testing"
        default_sql = f"/Users/{default_user}/Documents/Parity Testing/scripts"

        if non_interactive:
            base_path = os.environ.get("EP_INIT_BASE_PATH", default_base)
            sql_directory = os.environ.get("EP_INIT_SQL_DIR", default_sql)
        else:
            base_path = click.prompt("  Output directory for results", default=default_base)
            sql_directory = click.prompt("  SQL query files directory", default=default_sql)

        # Offer to create directories
        for dir_path, label in [(base_path, "Output"), (sql_directory, "SQL")]:
            p = Path(dir_path)
            if not p.exists():
                if non_interactive or click.confirm(
                    f"  {label} directory doesn't exist. Create it?", default=True
                ):
                    p.mkdir(parents=True, exist_ok=True)
                    click.echo(f"    Created: {p}")

        # Default db_target
        db_target = "ep15-qa ep20-qa"
        if not non_interactive:
            click.echo("")
            click.echo("  Default --db_target (used when not specified on command line):")
            click.echo("    Common choices: 'ep15-qa ep20-qa' (parity test QA)")
            click.echo("                    'ep15-dev ep20-dev' (parity test Dev)")
            click.echo("                    'ep15-qa' (single DB)")
            db_target = click.prompt(
                "  Default db_target",
                default="ep15-qa ep20-qa",
            )

    # --- Write files ---
    click.echo("")
    if env_path is not None:
        _write_env_file(env_path, env_credentials)
        click.echo("  Writing .env ... done")

    if paths_path is not None:
        _write_paths_config(paths_path, base_path, sql_directory, db_target)
        click.echo("  Writing paths_config.ini ... done")

    # --- Run validation ---
    click.echo("\nRunning validation...")
    from ep_parity.cli.validate_cmd import (
        _check_env_file,
        _check_paths_config,
        _check_sql_directory_contents,
    )

    _check_env_file(config_dir)
    _check_paths_config(config_dir)
    _check_sql_directory_contents(config_dir)

    click.echo("")
    click.echo("Setup complete! Next steps:")
    click.echo("  1. Connect to VPN")
    click.echo("  2. ep-parity validate --check-db")
    click.echo("  3. ep-parity export --emp_ids <ID> --db_target ep15-qa --db_target ep20-qa")
    click.echo("")
    click.echo("To edit credentials later, modify .env directly or re-run 'ep-parity init'.")
    click.echo("")
