"""ep-parity init: Interactive setup wizard for first-time configuration."""

import os
from pathlib import Path
from urllib.parse import quote_plus

import click

from ep_parity.utils.logging import get_logger

logger = get_logger("cli.init")

# Known database hostnames per environment
DB_HOSTS: dict[str, dict[str, str]] = {
    "qa": {
        "pri": "primary-portal-db.qa.internal.marathon-health.com",
        "rep": "primary-pariveda-db.qa.internal.marathon-health.com",
        "dbname": "portal_qa",
    },
    "dev": {
        "pri": "primary-portal-db.dev.internal.marathon-health.com",
        "rep": "primary-pariveda-db.dev.internal.marathon-health.com",
        "dbname": "portal_dev",
    },
    "prod": {
        "pri": "primary-portal-db.prod.internal.marathon-health.com",
        "rep": "primary-pariveda-db.prod.internal.marathon-health.com",
        "dbname": "portal_production",
    },
}


def _build_uri(username: str, password: str, host: str, dbname: str) -> str:
    """Build a PostgreSQL URI with properly escaped credentials."""
    safe_user = quote_plus(username)
    safe_pass = quote_plus(password)
    return f"postgresql://{safe_user}:{safe_pass}@{host}:5432/{dbname}"


def _mask_password(uri: str) -> str:
    """Show URI with password masked for confirmation display."""
    import re
    return re.sub(r"://([^:]+):([^@]+)@", r"://\1:****@", uri)


def _write_env_file(output_path: Path, uris: dict[str, str], env: str) -> None:
    """Write .env file with database URIs."""
    lines = [
        "# EP Parity Database Credentials",
        f"# Generated by 'ep-parity init' for {env} environment",
        "# NEVER commit this file to version control.",
        "",
    ]

    env_var_map = {
        "pri": "DB_PRIMARY_URI",
        "rep": "DB_REPLICATED_URI",
    }

    for target, env_var in env_var_map.items():
        if target in uris:
            lines.append(f"{env_var}={uris[target]}")

    lines.append("")
    output_path.write_text("\n".join(lines))


def _write_paths_config(
    output_path: Path, base_path: str, sql_directory: str, db_target: str
) -> None:
    """Write paths_config.ini file."""
    lines = [
        "[paths]",
        f"base_path = {base_path}",
        f"sql_directory = {sql_directory}",
        "",
        "[output]",
        "directory_format = {emp_id} {date} {time}",
        "date_format = %%m-%%d-%%y %%H%%M",
        "",
        "[defaults]",
        f"db_target = {db_target}",
        "",
    ]
    output_path.write_text("\n".join(lines))


@click.command()
@click.option(
    "--non-interactive",
    is_flag=True,
    help="Read from environment variables instead of prompting (for CI/automation).",
)
@click.pass_context
def init(ctx: click.Context, non_interactive: bool) -> None:
    """Interactive setup wizard for first-time configuration.

    Creates .env and paths_config.ini with your database credentials
    and directory paths. Handles password escaping automatically.

    Examples:

        ep-parity init

        EP_INIT_DB_USER=jane EP_INIT_DB_PASS=secret EP_INIT_ENV=qa \\
            ep-parity init --non-interactive
    """
    config_dir = Path(ctx.obj.get("config_dir") or ".")
    env_path = config_dir / ".env"
    paths_path = config_dir / "paths_config.ini"

    click.echo("")
    click.echo("EP Parity -- First-Time Setup")
    click.echo("=" * 40)
    click.echo("")
    click.echo("This will create .env and paths_config.ini")
    click.echo(f"in: {config_dir.resolve()}")
    click.echo("")

    # Check for existing files
    for path, name in [(env_path, ".env"), (paths_path, "paths_config.ini")]:
        if path.exists():
            if non_interactive:
                click.echo(f"  Overwriting existing {name}")
            elif not click.confirm(f"  {name} already exists. Overwrite?", default=False):
                click.echo(f"  Keeping existing {name}")
                if name == ".env":
                    env_path = None
                else:
                    paths_path = None

    if env_path is None and paths_path is None:
        click.echo("\nNothing to do. Both files kept as-is.")
        return

    # --- Collect credentials ---
    if env_path is not None:
        click.echo("\nDatabase Credentials:")
        click.echo("  (These are used to connect to Marathon Health databases via VPN)")
        click.echo("")

        if non_interactive:
            username = os.environ.get("EP_INIT_DB_USER", "")
            password = os.environ.get("EP_INIT_DB_PASS", "")
            env = os.environ.get("EP_INIT_ENV", "qa")
            if not username or not password:
                click.echo("  [FAIL] EP_INIT_DB_USER and EP_INIT_DB_PASS must be set")
                raise SystemExit(1)
        else:
            username = click.prompt("  Database username")
            password = click.prompt("  Database password", hide_input=True)
            env = click.prompt(
                "  Environment",
                type=click.Choice(["qa", "dev", "prod"], case_sensitive=False),
                default="qa",
            )

        if env not in DB_HOSTS:
            click.echo(f"  [FAIL] Unknown environment: {env}")
            raise SystemExit(1)

        hosts = DB_HOSTS[env]
        uris = {
            "pri": _build_uri(username, password, hosts["pri"], hosts["dbname"]),
            "rep": _build_uri(username, password, hosts["rep"], hosts["dbname"]),
        }

        click.echo("")
        click.echo(f"  Building connection URIs for {env.upper()} environment...")
        click.echo(f"    Primary:    {_mask_password(uris['pri'])}")
        click.echo(f"    Replicated: {_mask_password(uris['rep'])}")

    # --- Collect paths ---
    if paths_path is not None:
        click.echo("\nPaths:")
        default_user = os.getenv("USER", "user")
        default_base = f"/Users/{default_user}/Documents/Parity Testing"
        default_sql = f"/Users/{default_user}/Documents/Parity Testing/scripts"

        if non_interactive:
            base_path = os.environ.get("EP_INIT_BASE_PATH", default_base)
            sql_directory = os.environ.get("EP_INIT_SQL_DIR", default_sql)
        else:
            base_path = click.prompt("  Output directory for results", default=default_base)
            sql_directory = click.prompt("  SQL query files directory", default=default_sql)

        # Offer to create directories
        for dir_path, label in [(base_path, "Output"), (sql_directory, "SQL")]:
            p = Path(dir_path)
            if not p.exists():
                if non_interactive or click.confirm(
                    f"  {label} directory doesn't exist. Create it?", default=True
                ):
                    p.mkdir(parents=True, exist_ok=True)
                    click.echo(f"    Created: {p}")

        db_target = "both"
        if not non_interactive:
            db_target = click.prompt(
                "  Default db_target",
                type=click.Choice(["both", "primary", "replicated"], case_sensitive=False),
                default="both",
            )

    # --- Write files ---
    click.echo("")
    if env_path is not None:
        _write_env_file(env_path, uris, env)
        click.echo(f"  Writing .env ... done")

    if paths_path is not None:
        _write_paths_config(paths_path, base_path, sql_directory, db_target)
        click.echo(f"  Writing paths_config.ini ... done")

    # --- Run validation ---
    click.echo("\nRunning validation...")
    from ep_parity.cli.validate_cmd import (
        _check_env_file,
        _check_paths_config,
        _check_sql_directory_contents,
    )

    _check_env_file(config_dir)
    _check_paths_config(config_dir)
    _check_sql_directory_contents(config_dir)

    click.echo("")
    click.echo("Setup complete! Next steps:")
    click.echo("  1. Connect to VPN")
    click.echo("  2. ep-parity validate --check-db")
    click.echo("  3. ep-parity export --emp_ids <ID> --db_target both")
    click.echo("")
